apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: airflow-triggerer-claim1
  name: airflow-triggerer-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: sbs-5k