apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow.datapipeline.sa-scw.fr
  namespace: pipeline-namespace
spec:
  secretName: airflow-webserver-datapipeline-scw-tls
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  commonName:  airflow.datapipeline.sa-scw.fr
  dnsNames:
    - airflow.datapipeline.sa-scw.fr
