apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: airflow-triggerer-claim3
  name: airflow-triggerer-claim3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sbs-default