apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: datanode-claim0
  name: datanode-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: sbs-15k