apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: hive-db-volume
  name: hive-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: sbs-15k