apiVersion: v1
kind: Service
metadata:
  name: hive-postgres
  labels:
    io.kompose.service: hive-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: hive-postgres
