apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: warehouse
  name: warehouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sbs-15k