apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zeppelin
  name: zeppelin-service
spec:
  ports:
    - name: "2020"
      port: 2020
      targetPort: 8080
  selector:
    io.kompose.service: zeppelin
